resolver: lts-13.25  # GHC 8.6.5

packages:
  - servant/
  - servant-client-core/
  - servant-client/
  - servant-conduit
  - servant-docs/
  - servant-foreign/
  - servant-machines/
  - servant-pipes/
  - servant-server/
