# resolver: lts-13.25  # GHC 8.6.5
# resolver: lts-12.26  # GHC 8.4.4
resolver: lts-12.0  # GHC 8.4.3


packages:
  - servant/
  - servant-client-core/
  - servant-client/
  - servant-conduit
  - servant-docs/
  - servant-foreign/
  - servant-machines/
  - servant-pipes/
  - servant-server/
